#! /usr/bin/env bash
# 
# Space Robotics Challenge, Phase 2
# Copyright (c) 2019-2021, NASA-JSC. All Rights Reserved
# Unauthorized Distribution Strictly Prohibited
#

# move to this directory
_this_dir="$( cd "$(dirname "$0")" ; pwd -P )"
pushd `pwd` > /dev/null 2>&1
cd $_this_dir

# Source helper scripts
source "srcp2_setup.bash"

image_tag="scheducation/srcp2_comp:final_competitor"

sim_container_name="srcp2-final"
cmp_container_name="competitor-final"

# container constraints
use_local="false"
cpus=4
mem="5g"

cmp_volumes=""

# Main SIM Ros Master Network Name
simalias_name="simmaster"
srcp2net_name="srcp2net"

function help(){
    echo -e "${B}Summary:${rs}

    This script manages the docker containers necessary to run the Space 
    Robotics Simulation (Final). It starts the Docker containers, and 
    configures the host correctly for XServer forwarding.
    
    Note that all short-form options are case-sensitive

${B}General Options:${rs}
    
    ${B}-h | --help${rs}
        Show this message and quit

    ${B}-L | --local-docker${rs}
        Use the local versions of the docker images (if they exist). This overrides
        the default behaviour, which is to search for updates each time this
        script is run.

   ${B}-d | --developer${rs}
        Developer mode with '/home/srcp2/cmp_workspace' from to host folder

   ${B}-i | --interactive${rs}
        Simply launch as normal, but override all runtime args with
        interactive BASH shell

   ${B}-c | --cpus${rs}
        Set number of CPUs available to this container. Default is ${cpus}

   ${B}-m | --mem${rs}
        Set GB of RAM available to this container. Default is ${mem}
        Throttling this may result in undefined behavior

${B}Copyright${rs}
    
    Space Robotics Challange, Phase 2
    Copyright (c) 2019, 2020, 2021, NASA-JSC. All Rights Reserved
    Unauthorized Distribution Strictly Prohibited
"
}

# ______________________________________________________________________________________________________________________
echo_header
echo -e "${B}From host system:${rs}\n"

for arg in "$@"; do
  shift
  case "$arg" in
    "--help")        set -- "$@" "-h" ;;
    "--local-docker") set -- "$@" "-L" ;;
    "--interactive")  set -- "$@" "-i" ;;
    "--developer")  set -- "$@" "-d" ;;
    #
    "--cpus") set -- "$@" "-c";;
    "--mem")  set -- "$@" "-m";;
    *) set -- "$@" "$arg"
  esac
done

OPTIND=1
while getopts hC:dl:nd:Lic:m: arg; do
    case $arg in

        h)
            help
            exit 0
            ;;
        L)
            use_local="true"
            ;;
        d)
            cmp_volumes="developer"
            ;;
        i)
            interactive="-it"
            override_command="/bin/bash"
            ;;
        c)
            cpus=$OPTARG
            ;;
        m)
            mem="${OPTARG}g"
            ;;
        *)
            echo -e "$echo_error input option '$arg' is not supported"
            quit_with_popd 1
            ;;
    esac
done



# update docker images
if [[ "$use_local" == "false" ]]; then
    if ! docker pull $image_tag; then
        echo -e "$echo_error Docker pull failed"
        exit 1
    fi
    echo -e "$echo_ok image update complete"
else
    echo -e "$echo_warn Using local versions of the docker images, will ${B}not${rs} check Dockerhub for updates"
fi



# Display run state information to user (dev and comp)
echo
echo -e "$echo_info running image    : ${b}$image_tag${rs}"
echo -e "$echo_info container name   : ${b}$cmp_container_name${rs}"
echo -e "$echo_info volumes from name: ${b}$sim_container_name${rs}"


if [ -z $interactive ]; then
    echo
    echo -e "$echo_info Simulation container started. Gazebo startup typically takes a few seconds"
    echo -e "$echo_info run ${b}docker kill $container_name${rs} to stop, or await sim timeout"
else
    echo
    echo -e "$echo_info Running in interactive mode. Starting a BASH shell..."
fi

echo

# Setup the Host Volume 
echo
if [[ $cmp_volumes =~ "developer" ]]; then
    cmp_host_path=$(cd ../../cmp_workspace && pwd)
    if [[ ! -d $cmp_host_path ]]; then
        echo -e "$echo_error This machine does not have access to competitor source code. ${r}Cannot run as developer!${rs} Nice try"
        exit 1
    fi
    cmp_volumes="--volume=${cmp_host_path}:/home/srcp2/cmp_workspace:rw"
fi
echo


echo -e "$echo_info Confirming Network Setup: ${b} Network Setup${rs}..."
if ! docker network ls | grep -q "$srcp2net_name"; then
    echo -e "$echo_info Setting up as ${b} Bridge $srcp2net_name${rs}"
    docker network create --driver=bridge $srcp2net_name
    echo 
else
    echo -e "$echo_info Existing network found: ${b}$srcp2net_name${rs}"
fi
echo -e "$echo_info Network Setup is now ${b} ready as $srcp2net_name${rs}..."
echo

echo -e "${B}________________________________________________________________________________________________________________________${rs}"
echo -e "${B}From Container:${rs}"
echo


#    $cmp_volumes \


docker run --rm  \
    --name $cmp_container_name\
    --user 1001:1001 \
    $interactive \
    --network $srcp2net_name \
    --network-alias $simalias_name \
    --env=ROS_MASTER_URI="http://${simalias_name}:11311" \
    --cpus=$cpus \
    --memory=$mem \
    $cmp_volumes \
    $image_tag  $override_command

exit $?
