# Define the goal
bool desired_state # The task to empty the bin
---
# Define the result
float64 final_angle # 
---
# Define a feedback message
float64 current_angle # Not using in current implementation due to lack of a feedback topic