# Define the goal
float32 forward_velocity  # For manual driving
float32 angular_velocity  # For manual driving

geometry_msgs/PointStamped point # Will not contain orientation information

geometry_msgs/PoseStamped pose   # Will contain orientation information
bool manual_driving              # Whether or not this is a manual drive
---
# Define the result
# TODO: Make an enum (in utils?) to properly define these
# 0: Failed
# 1: Succeeded
# 2: Interrupted by a manual action
uint32 result
---
# Define a feedback message
float32 percent_complete